"""Validated output schema for LLM classification.

Every field is constrained. Enums are closed, so a label the model invents
fails validation rather than quietly entering the dataset. This is the first
of two anti-fabrication controls; the second is quote grounding, which is
verified in Python after the response returns (see verify_excerpt).
"""

from __future__ import annotations

import re
import unicodedata
from typing import Literal

from pydantic import BaseModel, Field

from .taxonomy import FEEDBACK_TYPE_NAMES, STAGE_NAMES, THEME_NAMES

# Literal types are built from the taxonomy so the two can never drift apart.
JourneyStage = Literal[STAGE_NAMES]      # type: ignore[valid-type]
Theme = Literal[THEME_NAMES]             # type: ignore[valid-type]
FeedbackType = Literal[FEEDBACK_TYPE_NAMES]  # type: ignore[valid-type]


class FeedbackClassification(BaseModel):
    """The 9 fields the model produces for one feedback post."""

    is_relevant: bool = Field(
        description="True only if this post is about configuring, running, or "
                    "governing Port self-service actions, workflows, or "
                    "automations. False for catalog modelling, dashboards, "
                    "integrations, scorecards, and other unrelated areas."
    )
    primary_theme: Theme = Field(
        description="The single best-fitting theme. Must be one of the allowed values."
    )
    journey_stage: JourneyStage = Field(
        description="Where in the action setup journey the user is stuck."
    )
    feedback_type: FeedbackType = Field(
        description="The nature of the feedback."
    )
    severity: int = Field(
        ge=1, le=5,
        description="1 = nice to have, 5 = blocking with no workaround."
    )
    short_summary: str = Field(
        min_length=10, max_length=200,
        description="One plain sentence describing the problem, in business "
                    "language. No jargon, no restating the title."
    )
    user_need: str = Field(
        min_length=10, max_length=200,
        description="What the user is ultimately trying to achieve, phrased as "
                    "a need rather than a solution."
    )
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="How certain you are of this classification. Be honest: "
                    "use below 0.7 when the post is vague or spans areas."
    )
    evidence_excerpt: str = Field(
        min_length=10, max_length=300,
        description="A short quote copied EXACTLY from the post text. Must "
                    "appear verbatim in the source. Never paraphrase."
    )


class AnalyzedRecord(BaseModel):
    """A classification joined to its source record, with provenance."""

    feedback_id: str
    title: str
    votes: int | None
    comments_count: int | None
    status: str | None
    category: str | None
    created_at: str | None
    source_url: str

    classification: FeedbackClassification

    # provenance -- recorded so any figure can be traced to what produced it
    model_name: str
    prompt_version: str
    analyzed_at: str
    # computed in Python, never generated by the model
    evidence_verified: bool


# --- quote grounding -------------------------------------------------------
_WS = re.compile(r"\s+")


def _norm(text: str) -> str:
    """Normalise for substring comparison without weakening the check.

    Only unicode form, whitespace, and quote style are relaxed -- the words
    themselves must still match exactly.
    """
    text = unicodedata.normalize("NFKC", text or "")
    text = text.replace("’", "'").replace("‘", "'")
    text = text.replace("“", '"').replace("”", '"')
    text = text.replace("–", "-").replace("—", "-")
    return _WS.sub(" ", text).strip().lower()


MIN_GROUNDED_WORDS = 6


def verify_excerpt(excerpt: str, source_text: str) -> bool:
    """True if the excerpt appears verbatim in the source."""
    if not excerpt or not source_text:
        return False
    return _norm(excerpt) in _norm(source_text)


def ground_excerpt(excerpt: str, source_text: str) -> tuple[bool, str]:
    """Return (verified, excerpt_to_display).

    Structured-output generation occasionally appends stray characters to the
    end of a string field -- observed in practice as a trailing brace, a lone
    quote mark, a CJK character, or a fragment of the model's own commentary.
    The quoted words themselves are correct; only the tail is corrupt.

    Rather than discard an otherwise-valid quote, trim trailing words until
    what remains is a genuine substring of the source, and display only that.
    This *tightens* the guarantee: whatever is shown to a user has been
    verified character-for-character against the source text.

    A quote that cannot be grounded to at least MIN_GROUNDED_WORDS words is
    rejected outright and never displayed.
    """
    if not excerpt or not source_text:
        return False, excerpt

    if verify_excerpt(excerpt, source_text):
        return True, excerpt.strip()

    words = excerpt.split()
    for end in range(len(words) - 1, MIN_GROUNDED_WORDS - 1, -1):
        candidate = " ".join(words[:end])
        if verify_excerpt(candidate, source_text):
            return True, candidate.rstrip(" ,;:-\"'").strip()

    # Leading garbage is rarer, but check before giving up.
    for start in range(1, min(4, len(words) - MIN_GROUNDED_WORDS)):
        candidate = " ".join(words[start:])
        if verify_excerpt(candidate, source_text):
            return True, candidate.strip()

    return False, excerpt
